### PR TITLE
Fix performance beatmap info

### PR DESCRIPTION
**Pull request by tsunyoku**

### CODE REVIEW

**Comment by tsunyoku** [comment]
FUICASDY GOFIPASDPFOIUGASDFASDFHPOGUIG

**Comment by lenforiee** [comment]
bro did it again

**Comment by RealistikDash** [comment]
Current shots tally: 4

**Comment by 7ez** [comment]
realistikosu rewrite including ftp and rabbitmq!

**Comment by tsunyoku** [comment]
> realistikosu rewrite including ftp and rabbitmq!

and s3!
and performance-service!

**Comment by blobnom** [comment]
and tornado! (aochi's favorite web framework)

**Comment by 7ez** [comment]
this is ussr not pep.py

**Pull request closed without merging**
