### PR TITLE
Recalculation based pubsubs

### PR DESCRIPTION
**Pull request by RealistikDash**
Expands the recalculation capabilities, offering a redis api for access.

Adds the pubsubs:
`ussr:recalculate_user` - Performs a PP and accuracy recalculation.
`ussr:recalculate_user_full` - Recalculates the users pp, acc, max combo, total score and ranked score.

### CODE REVIEW

**Comment by RealistikDash** [comment]
I, RealistikDash, conclude my code is good.

**Comment by 7ez** [comment]
nooooo

**Comment by 7ez** [comment]
he has merged the broken

**Comment by 7ez** [comment]
:trollface:

**Pull request merged**
