### PR TITLE
remove leaderboard cache & rework leaderboard logic

### PR DESCRIPTION
**Pull request by tsunyoku**
big ass change. removes cache and replaces it with a heavily optimized query. this should never need to be touched. tested on my local instance with akat db

raw fetching speeds are ofc slightly slower than our cache however this removes memory issues aswell as the service becoming slower with time as the cache expands. 

there's also been some bugs with score statuses recently and i believe the cache is the culprit.

### CODE REVIEW

**Comment by tsunyoku** [comment]
ffs

**Comment by NiceAesth** [comment]
Nice PR My Friend

**Comment by tsunyoku** [comment]
> Nice PR My Friend

SHut up

**Comment by 7ez** [comment]
james try not to pr to the base repo challenge

**Pull request closed without merging**
