### PR TITLE
epic webhook redesign

### PR DESCRIPTION
**Pull request by 7ez**

### CODE REVIEW

**Comment by 7ez** [comment]
troll

**Comment by RealistikDash** [comment]
Oh right I will test it right now lmfao

**Comment by 7ez** [comment]
DAMN JUST NOW

**Comment by RealistikDash** [comment]
I am one with the speed

**Comment by 7ez** [comment]
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
handlers/score_sub.py
objects/score.py

**Comment by 7ez** [comment]
fuck you github

**Comment by RealistikDash** [comment]
I'll merge and then test ig.

**Pull request merged**
