### PR TITLE
feat: allow supporters to view lb's on unranked maps

### PR DESCRIPTION
**Pull request by 7ez**

### CODE REVIEW

**Comment by blobnom** [comment]
you should also fix mod lbs while you're at it

**Comment by 7ez** [comment]
> you should also fix mod lbs while you're at it

do they not work

**Comment by blobnom** [comment]
> > you should also fix mod lbs while you're at it
> 
> do they not work

I dont know how to explain it with words so i will explain it with images
my local scores have nomod and HDHR but since nomod is my best score on the map it will only show my nomod score on nomod leaderboards, it wont show the hdhr score on hdhr lbs
image
image
image

**Comment by RealistikDash** [comment]
The issue mr blobnom is describing is mod lbs only considering users' top scores on a map, which differs from bancho's.

**Comment by blobnom** [comment]
yes correct thank you

**Review by RealistikDash — APPROVED** [review]
Looks good!

**Pull request merged**
